BOT_TOKEN = "8584515211:AAGhAC51MBFBLdqWf4slISe9c4ZRIe5bpF8"
ADMIN_USERNAME = "cruxifeed"

VIP_PRICE = 30
VIP_DAYS = 30

PAIRS = ["EURUSD","GBPUSD","USDJPY","USDCAD","AUDUSD","USDCNY"]
TIMEFRAMES = ["5s","15s","30s","1m","3m","5m"]

MIN_AUTO_TRADES = 5
MAX_AUTO_TRADES = 12
AUTO_SIGNAL_DELAY = 60  # 1 minute reminder

BUY_IMAGE_PATH = "buy.png"
SELL_IMAGE_PATH = "sell.png"